name: wz143
description: wz143
repository: https://github.com/KosmicDevs/wz143

environment:
  sdk: ^3.3.0

dependencies:
  dotenv: ^4.2.0
  nyxx: ^6.1.0
  nyxx_commands: ^6.0.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
